name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./
          tags: ghcr.io/seicho-group/kotovskaya:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    permissions:
      contents: read
      packages: read
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker stop kotovskaya
            sudo docker rm -f kotovskaya
            sudo docker pull ghcr.io/seicho-group/kotovskaya:latest
            sudo docker run --name kotovskaya -p 80:80 -d ghcr.io/seicho-group/kotovskaya:latest